### ISSUE TITLE
Git LFS is over its data bandwidth quota

### ISSUE THREAD

**Issue by bact** [PyThaiNLP/prachathai-67k#3]
Found an issue on getting the actual corpus in data.zip since it's in Git LFS and looks like the storage reached its bandwidth quota.

Error message:
```
Downloading data.zip (254 MB)
Error downloading object: data.zip (e28bd1a): Smudge error: Error downloading data.zip 
(e28bd1a15c17eeab8e606aef50463246d46e23f47389b12501c369f99eedb38a): batch response: 
This repository is over its data quota. Account responsible for LFS bandwidth should purchase 
more data packs to restore access.
```

**Comment by wannaphong** [comment]
wait 24 days for reset.
![ภาพ](https://user-images.githubusercontent.com/8536487/113484146-f2a5e980-94d0-11eb-9f76-199c0af59bb2.png)
